import argparse
import torch
import numpy as np
import pypose as pp
from pathlib import Path

from DataLoader import SequenceBase, StereoFrame, smart_transform
from Evaluation.EvalSeq import EvaluateSequences
from Odometry.MACVO import MACVO

from Utility.Config import load_config, asNamespace
from Utility.PrettyPrint import print_as_table, ColoredTqdm, Logger
from Utility.Sandbox import Sandbox
from Utility.Visualize import fig_plt, rr_plt
from Utility.Timer import Timer


def _build_data_root_suffix(data_root: str) -> str | None:
    root = Path(data_root)
    parts = [p for p in root.parts if p not in {"/", "\\", ""}]
    if len(parts) >= 2:
        return f"{parts[-2]}_{parts[-1]}"
    if len(parts) == 1:
        return parts[-1]
    return None


def _load_saved_pose_se3(exp_space: Sandbox) -> torch.Tensor:
    for filename in ("poses.csv", "poses.npy"):
        pose_path = exp_space.path(filename)
        if not pose_path.exists():
            continue
        if pose_path.suffix == ".csv":
            data = np.loadtxt(pose_path, delimiter=",", skiprows=1, dtype=float)
        else:
            data = np.load(pose_path)
        if data.ndim == 1:
            data = data.reshape(1, -1)
        return torch.tensor(data[:, 1:])
    raise FileNotFoundError(f"No poses.csv or poses.npy found under {exp_space.folder}")


def VisualizeRerunCallback(frame: StereoFrame, system: MACVO, pb: ColoredTqdm):
    rr_plt.set_time_sequence("frame_idx", frame.frame_idx)

    # Non-key frame does not need visualization
    if system.graph.frames.data["need_interp"][-1]: return

    if frame.frame_idx > 0:
        rr_plt.log_trajectory("/world/est", pp.SE3(system.graph.frames.data["pose"].tensor))

    rr_plt.log_camera("/world/macvo/cam_left", pp.SE3(system.graph.frames.data["pose"][-1]), system.graph.frames.data["K"][-1])
    rr_plt.log_image ("/world/macvo/cam_left", frame.stereo.imageL[0].permute(1, 2, 0))

    map_points = system.graph.get_frame2map(system.graph.frames[-1:])
    rr_plt.log_points("/world/point_cloud", map_points.data["pos_Tw"], map_points.data["color"], map_points.data["cov_Tw"], "sphere")

    vo_points  = system.graph.get_match2point(system.graph.get_frame2match(system.graph.frames[-1:]))
    rr_plt.log_points("/world/vo_tracking", vo_points.data["pos_Tw"], vo_points.data["color"], vo_points.data["cov_Tw"], "sphere")


def VisualizeIMUData(frame: StereoFrame, system: MACVO):
    if (not hasattr(frame, "imu")) or (getattr(frame, "imu") is None):
        return

    imu = frame.imu
    if imu.time_ns.numel() == 0:
        return

    imu_time_ns = imu.time_ns.reshape(-1).detach().cpu().long()
    imu_acc = imu.acc.reshape(-1, 3).detach().cpu().float()
    imu_gyro = imu.gyro.reshape(-1, 3).detach().cpu().float()

    # Log tri-axis IMU as time-series lines under two groups: /imu/acc/* and /imu/gyro/*
    for i in range(imu_time_ns.numel()):
        rr_plt.set_time_sequence("imu_ns", int(imu_time_ns[i].item()))
        rr_plt.log_scalar("/imu/acc/x", float(imu_acc[i, 0].item()))
        rr_plt.log_scalar("/imu/acc/y", float(imu_acc[i, 1].item()))
        rr_plt.log_scalar("/imu/acc/z", float(imu_acc[i, 2].item()))
        rr_plt.log_scalar("/imu/gyro/x", float(imu_gyro[i, 0].item()))
        rr_plt.log_scalar("/imu/gyro/y", float(imu_gyro[i, 1].item()))
        rr_plt.log_scalar("/imu/gyro/z", float(imu_gyro[i, 2].item()))


def VisualizeVRAMUsage(frame: StereoFrame, system: MACVO, pb: ColoredTqdm):
    if torch.cuda.is_available():
        allocated_memory = torch.cuda.memory_reserved(0) / 1e9  # Convert to GB
        allocated_memory = f"{round(allocated_memory, 3)} GB"
    else:
        allocated_memory = "N/A"

    pb.set_description(desc=f"{system.graph}, VRAM={allocated_memory}")

def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--odom", type=str, default = "Config/Experiment/MACVO/MACVO_Fast_IMU.yaml")
    parser.add_argument("--data", type=str, default = "Config/Sequence/holoocean_imu.yaml")
    parser.add_argument(
        "--seq_to",
        type=int,
        default=None,
        help="Crop sequence to frame# when ran. Set to -1 (default) if wish to run whole sequence",
    )
    parser.add_argument(
        "--seq_from",
        type=int,
        default=0,
        help="Crop sequence from frame# when ran. Set to 0 (default) if wish to start from first frame",
    )
    parser.add_argument(
        "--resultRoot",
        type=str,
        default="./Results",
        help="Directory to store trajectory and files generated by the script."
    )
    parser.add_argument(
        "--useRR",
        default=False,
        action="store_true",
        help="Activate live Rerun visualization and save a compact rerun.rrd into the result sandbox.",
    )
    parser.add_argument(
        "--live-display",
        action="store_true",
        help="Serve a non-blocking local browser dashboard with live IMU-center poses.",
    )
    parser.add_argument(
        "--dashboard-host",
        type=str,
        default="127.0.0.1",
        help="Host for the live dashboard HTTP server.",
    )
    parser.add_argument(
        "--dashboard-port",
        type=int,
        default=8765,
        help="Port for the live dashboard HTTP server.",
    )
    parser.add_argument(
        "--saveplt",
        action="store_true",
        help="Activate PLTVisualizer to generate <frame_idx>.jpg file in space folder for covariance visualization.",
    )
    parser.add_argument(
        "--preload",
        action="store_true",
        help="Preload entire trajectory into RAM to reduce data fetching overhead during runtime."
    )
    parser.add_argument(
        "--autoremove",
        action="store_true",
        help="Cleanup result sandbox after script finishs / crashed. Helpful during testing & debugging."
    )
    parser.add_argument(
        "--noeval",
        default=True,
        action="store_true",
        help="Evaluate sequence after running odometry."
    )
    parser.add_argument(
        "--timing",
        action="store_true",
        help="Record timing for system (active Utility.Timer for global time recording)"
    )
    parser.add_argument(
        "--adaptive",
        action="store_true",
        help="Enable adaptive_v1 (VisualHealthGate) mode: dynamically selects IMU constraints per frame pair"
    )
    parser.add_argument(
        "--adaptive-v2",
        action="store_true",
        dest="adaptive_v2",
        help="Enable adaptive_v2 (VisualHealthGateV2) mode: uses frontend flow covariance for gating"
    )
    parser.add_argument(
        "--adaptive-v3a",
        action="store_true",
        dest="adaptive_v3a",
        help="Enable adaptive_v3a (VisualHealthGateV3) mode: binary pure/full gate via running median flow_cov"
    )
    parser.add_argument(
        "--v3a-force",
        type=str,
        default="",
        help="v3a force mode: 'pure', 'full', 'pure2latch', 'latch'"
    )
    parser.add_argument(
        "--adaptive-v3b",
        action="store_true",
        dest="adaptive_v3b",
        help="Enable adaptive_v3b (VisualHealthGateV3b) mode: 3-detector state machine"
    )
    parser.add_argument(
        "--v3b-force",
        type=str,
        default="",
        help="v3b force mode: 'rotation_only', 'pure_macvo', 'full_imu'"
    )
    parser.add_argument(
        "--v3b-reset-velocity-on-full-enter",
        action="store_true",
        dest="v3b_reset_velocity_on_full_enter",
        help="Ablation: reset IMU velocity state to zero on full_imu entry"
    )
    parser.add_argument(
        "--v3b-visual-collapse-sustain",
        type=int,
        default=None,
        dest="v3b_visual_collapse_sustain",
        help="Ablation D4: override visual_collapse_sustain (default=5). Set to 1 for D4."
    )
    parser.add_argument(
        "--v3b-d2-rerun-on-vc",
        action="store_true",
        dest="v3b_d2_rerun_on_vc",
        help="Ablation D2: re-run current pair with full_imu when visual_collapse triggers"
    )
    parser.add_argument(
        "--v3b-d2-vc-sustain",
        type=int,
        default=None,
        dest="v3b_d2_vc_sustain",
        help="Ablation D2+D4: override VC sustain specifically for D2 rerun (separate from D4 sustain)"
    )
    parser.add_argument(
        "--v3b-vc-mode",
        type=str,
        default=None,
        dest="v3b_vc_mode",
        choices=["single_level", "two_level"],
        help="VC mode: single_level (original V3b) or two_level (Rule B: severe<mild)"
    )
    parser.add_argument(
        "--v3b-vc-severe-thr",
        type=int,
        default=None,
        dest="v3b_vc_severe_num_res_thr",
        help="Two-level VC severe threshold (default=30)"
    )
    parser.add_argument(
        "--v3b-vc-severe-sustain",
        type=int,
        default=None,
        dest="v3b_vc_severe_sustain",
        help="Two-level VC severe sustain (default=1)"
    )
    parser.add_argument(
        "--v3b-vc-mild-thr",
        type=int,
        default=None,
        dest="v3b_vc_mild_num_res_thr",
        help="Two-level VC mild threshold (default=50)"
    )
    parser.add_argument(
        "--v3b-vc-mild-sustain",
        type=int,
        default=None,
        dest="v3b_vc_mild_sustain",
        help="Two-level VC mild sustain (default=5)"
    )
    parser.add_argument(
        "--v3b-fd-grace-enabled",
        action="store_true",
        dest="v3b_fd_grace_enabled",
        help="V3b++ Phase 1a: enable FD-E full_imu grace period (default: off)"
    )
    parser.add_argument(
        "--v3b-fd-grace-period",
        type=int,
        default=None,
        dest="v3b_fd_grace_period",
        help="V3b++ Phase 1a: FD grace period length in frames (default=30, only active when fd-grace-enabled)"
    )
    parser.add_argument(
        "--v3b-fd-cooldown",
        type=int,
        default=None,
        dest="v3b_fd_cooldown",
        help="V3b++ Phase 1b: override full_divergence_cooldown_frames (default=100). Shorter = faster re-attempt after FD"
    )
    parser.add_argument(
        "--imu-factor-mode",
        type=str,
        default=None,
        choices=["legacy_pose_prior", "preintegrated_vio", "local_inertial_ba"],
        dest="imu_factor_mode",
        help="Override TwoFrame_PGO IMU factor mode. local_inertial_ba enables the internal local inertial window.",
    )
    parser.add_argument(
        "--local-ba-window-size",
        type=int,
        default=None,
        dest="local_ba_window_size",
        help="Override local_inertial_ba window size. Must be >=3.",
    )
    parser.add_argument(
        "--local-ba-writeback",
        type=str,
        default=None,
        choices=["current", "all_optimized"],
        dest="local_ba_writeback",
        help="Which optimized local-window states to write back to the running trajectory.",
    )
    parser.add_argument(
        "--local-ba-free-first-frame",
        action="store_true",
        dest="local_ba_free_first_frame",
        help="Do not fix the oldest frame in the local inertial BA window.",
    )
    parser.add_argument(
        "--visual-cache-mode",
        type=str,
        choices=["off", "replay"],
        default="off",
        dest="visual_cache_mode",
        help="Replay cached visual factors without constructing or running the neural frontend.",
    )
    parser.add_argument(
        "--visual-cache-path",
        type=Path,
        default=None,
        dest="visual_cache_path",
        help="Schema-versioned visual-factor cache directory used by --visual-cache-mode replay.",
    )
    return parser.parse_args()


def _apply_optimizer_cli_overrides(args, odomcfg_dict: dict) -> None:
    optimizer_args = odomcfg_dict["optimizer"]["args"]
    if args.imu_factor_mode is not None:
        optimizer_args["imu_factor_mode"] = args.imu_factor_mode
    if args.local_ba_window_size is not None:
        if int(args.local_ba_window_size) < 3:
            raise ValueError("--local-ba-window-size must be >= 3")
        optimizer_args["local_ba_window_size"] = int(args.local_ba_window_size)
    if args.local_ba_writeback is not None:
        optimizer_args["local_ba_writeback"] = str(args.local_ba_writeback)
    if bool(args.local_ba_free_first_frame):
        optimizer_args["local_ba_fix_first_frame"] = False


def _apply_visual_cache_cli_overrides(args, odomcfg_dict: dict) -> None:
    mode = str(getattr(args, "visual_cache_mode", "off")).strip().lower()
    cache_path = getattr(args, "visual_cache_path", None)
    if mode == "off":
        if cache_path is not None:
            raise ValueError("--visual-cache-path requires --visual-cache-mode replay")
        return
    if mode != "replay":
        raise ValueError(f"unsupported visual cache mode: {mode!r}")
    if cache_path is None:
        raise ValueError("--visual-cache-path is required when --visual-cache-mode replay")

    odomcfg_dict["args"]["visual_cache_mode"] = "replay"
    odomcfg_dict["args"]["visual_cache_path"] = str(Path(cache_path))
    odomcfg_dict["frontend"] = {"type": "ReplayFrontend", "args": {}}


def _resolve_scene_name(datacfg) -> str:
    configured = getattr(datacfg.args, "scene", None)
    if isinstance(configured, str) and configured.strip():
        return configured.strip()
    return Path(str(datacfg.args.root)).name


def _build_run_readme(project_name, args, odomcfg, datacfg) -> str:
    using_imu_data = "imu" in str(datacfg.type).lower()
    motion_model = str(odomcfg.motion.type)
    optimizer = str(odomcfg.optimizer.type)
    frontend = str(odomcfg.frontend.type)

    steps = [
        "1. Load stereo (and optionally IMU) sequence from config.",
        f"2. Run frontend: {frontend} for depth/matching estimation.",
        f"3. Use motion prior: {motion_model}.",
        f"4. Run backend optimizer: {optimizer}.",
        "5. Save trajectory/map outputs and runtime artifacts.",
    ]

    if using_imu_data:
        steps.insert(3, "4. Consume IMU packet(s) for frame-to-frame motion initialization.")

    if args.useRR:
        steps.append("6. Stream visualization to Rerun and save rerun.rrd.")

    if args.live_display:
        steps.append("6. Serve a read-only browser dashboard with IMU-center MACVO raw, VIO committed, and GT states.")

    if args.saveplt:
        steps.append("7. Save matplotlib visual diagnostics.")

    lines = [
        f"# Run Summary: {project_name}",
        "",
        "## Runtime Arguments",
        f"- odom config: {args.odom}",
        f"- data config: {args.data}",
        f"- seq_from: {args.seq_from}",
        f"- seq_to: {args.seq_to}",
        f"- preload: {args.preload}",
        f"- useRR: {args.useRR}",
        f"- saveplt: {args.saveplt}",
        f"- timing: {args.timing}",
        "",
        "## Active Modules",
        f"- data type: {datacfg.type}",
        f"- frontend: {frontend}",
        f"- motion model: {motion_model}",
        f"- optimizer: {optimizer}",
        f"- outlier filter: {odomcfg.outlier.type}",
        "",
        "## Improvement Steps Executed",
    ]
    lines.extend([f"- {s}" for s in steps])

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    args = get_args()

    # Metadata setup & visualizer setup
    cfg, cfg_dict = load_config(Path(args.odom))
    odomcfg, odomcfg_dict = cfg.Odometry, cfg_dict["Odometry"]
    datacfg, datacfg_dict = load_config(Path(args.data))
    _apply_visual_cache_cli_overrides(args, odomcfg_dict)
    _apply_optimizer_cli_overrides(args, odomcfg_dict)
    cfg = asNamespace(cfg_dict)
    odomcfg = cfg.Odometry
    project_name = odomcfg.name + "@" + datacfg.name

    run_suffix = _build_data_root_suffix(str(datacfg.args.root))
    exp_space = Sandbox.create(Path(args.resultRoot), project_name, run_suffix=run_suffix)
    if args.autoremove: exp_space.set_autoremove()
    exp_space.config = {
        "Project": project_name,
        "Odometry": odomcfg_dict,
        "Data": {"args": datacfg_dict, "end_idx": args.seq_to, "start_idx": args.seq_from},
    }
    exp_space.path("README.md").write_text(_build_run_readme(project_name, args, odomcfg, datacfg), encoding="utf-8")

    _diag_writer = None
    _live_dashboard = None
    _online_pose_recorder = None
    try:
        # Setup logging and visualization
        if args.useRR:
            rr_plt.default_mode = "rerun"
            rrd_path = exp_space.path("rerun.rrd")
            exp_space.config["Rerun"] = {"rrd_path": str(rrd_path)}
            rr_plt.init_connect(project_name, rrd_path)

        if args.live_display:
            from Utility.LiveDashboard import LiveDashboard

            _live_dashboard = LiveDashboard.start(
                args.dashboard_host,
                args.dashboard_port,
                dataset_root=str(datacfg.args.root),
            )
            _live_dashboard.set_meta(
                project=project_name,
                scene=str(getattr(datacfg, "name", "scene")),
                mode="real data / current pipeline",
                url=f"http://{args.dashboard_host}:{args.dashboard_port}/",
            )
            Logger.write(
                "info",
                f"Live dashboard: http://{args.dashboard_host}:{args.dashboard_port}/ "
                "(read-only; IMU-center poses)",
            )

        Timer.setup(active=args.timing)
        fig_plt.default_mode = "image" if args.saveplt else "none"

        def onFrameFinished(frame: StereoFrame, system: MACVO, pb: ColoredTqdm):
            VisualizeRerunCallback(frame, system, pb)
            VisualizeIMUData(frame, system)
            VisualizeVRAMUsage(frame, system, pb)
            if _live_dashboard is not None:
                _live_dashboard.publish_system(system, frame, "macvo_raw")

        # Initialize data source
        sequence = smart_transform(
            SequenceBase[StereoFrame].instantiate(datacfg.type, datacfg.args).clip(args.seq_from, args.seq_to),
            cfg.Preprocess
        )

        if args.preload:
            sequence = sequence.preload()

        system = MACVO[StereoFrame].from_config(asNamespace(exp_space.config))

        from Utility.OnlinePoseRecorder import OnlinePoseRecorder

        _online_pose_recorder = OnlinePoseRecorder(
            exp_space.path("poses_online.csv"),
            output_world_frame=str(getattr(sequence, "pose_output_frame", "NED")),
        )
        system.on_optimize_writeback.append(_online_pose_recorder)

        if _live_dashboard is not None:
            # This hook runs after the previous backend result has been written
            # into the global graph, so it is the committed VIO state rather
            # than the frontend's current warm-start pose.
            system.on_optimize_writeback.append(
                lambda current: _live_dashboard.publish_system(current, None, "vio_committed")
            )

        # ── Setup frame-pair diagnostics writer ───────────────────────────
        from Utility.FramePairDiagnostics import FramePairDiagnosticsWriter
        scene_name = _resolve_scene_name(datacfg)
        _diag_writer = FramePairDiagnosticsWriter(
            exp_space.path("frame_pair_diagnostics.csv"),
            scene=scene_name,
            method=odomcfg.name,
        )
        system.set_diagnostics_writer(_diag_writer, scene=scene_name, method=odomcfg.name)

        # ── Load GT poses from ref_pose.csv for diagnostics ────────────
        ref_pose_path = Path(str(datacfg.args.root)) / "ref_pose.csv"
        if ref_pose_path.exists():
            import csv as _csv
            gt_positions: dict = {}
            gt_quaternions: dict = {}
            gt_velocities: dict = {}
            gt_angular_velocities: dict = {}
            with open(ref_pose_path, "r") as _f:
                reader = _csv.DictReader(_f)
                _has_quat = all(c in (reader.fieldnames or []) for c in ("qx", "qy", "qz", "qw"))
                _has_velocity = all(c in (reader.fieldnames or []) for c in ("vx", "vy", "vz"))
                _has_angular_velocity = all(c in (reader.fieldnames or []) for c in ("wx", "wy", "wz"))
                for _row in reader:
                    _ts = int(_row["timestamp"])
                    gt_positions[_ts] = (
                        float(_row.get("x_m", _row.get("x", 0))),
                        float(_row.get("y_m", _row.get("y", 0))),
                        float(_row.get("z_m", _row.get("z", 0))),
                    )
                    if _has_quat:
                        _qx = float(_row.get("qx", 0))
                        _qy = float(_row.get("qy", 0))
                        _qz = float(_row.get("qz", 0))
                        _qw = float(_row.get("qw", 1))
                        gt_quaternions[_ts] = (_qx, _qy, _qz, _qw)
                    if _has_velocity:
                        gt_velocities[_ts] = (
                            float(_row.get("vx", 0)),
                            float(_row.get("vy", 0)),
                            float(_row.get("vz", 0)),
                        )
                    if _has_angular_velocity:
                        gt_angular_velocities[_ts] = (
                            float(_row.get("wx", 0)),
                            float(_row.get("wy", 0)),
                            float(_row.get("wz", 0)),
                        )
            system.set_gt_positions(
                gt_positions,
                gt_quaternions if _has_quat else None,
                gt_velocities=gt_velocities if _has_velocity else None,
                gt_angular_velocities=(
                    gt_angular_velocities if _has_angular_velocity else None
                ),
            )
            _gt_info = ["positions"]
            if _has_quat:
                _gt_info.append("quaternions")
            if _has_velocity:
                _gt_info.append("world velocities")
            if _has_angular_velocity:
                _gt_info.append("body angular velocities")
            Logger.write("info", f"Loaded {len(gt_positions)} GT {'+'.join(_gt_info)} from {ref_pose_path}")

        # ── Generate metadata_usage_trace.json for audit ──────────────
        from Utility.MetadataUsageTrace import write_metadata_usage_trace
        write_metadata_usage_trace(Path(str(datacfg.args.root)), exp_space)

        # ── Enable adaptive_v3b if requested ────────────────────────────
        if getattr(args, "adaptive_v3b", False):
            from Utility.VisualHealthGateV3b import VisualHealthGateV3b, V3bConfig
            gate_cfg = V3bConfig()
            # Override defaults from CLI if provided
            for attr in ["default_mode", "visual_collapse_num_res_thr", "visual_collapse_sustain",
                         "full_div_rp_thr", "full_div_imu_trans_loss_thr", "full_div_sustain",
                         "rot_harm_rR_thr", "rot_harm_flow_cov_thr", "rot_harm_sustain",
                         "rot_harm_cooldown_frames", "full_divergence_cooldown_frames",
                         "full_imu_probation_min_frames",
                         "reset_velocity_on_full_enter",
                         "d2_rerun_on_vc", "d2_vc_sustain",
                         "vc_mode",
                         "vc_severe_num_res_thr", "vc_severe_sustain",
                         "vc_mild_num_res_thr", "vc_mild_sustain",
                         "fd_grace_enabled", "fd_grace_period"]:
                val = getattr(args, f"v3b_{attr}", None)
                if val is not None:
                    setattr(gate_cfg, attr, val)
            # velocity_reset_strategy is a string
            vrs = getattr(args, "v3b_velocity_reset_strategy", None)
            if vrs is not None:
                gate_cfg.velocity_reset_strategy = vrs
            force_mode = getattr(args, "v3b_force", "")
            if force_mode:
                gate_cfg.force_mode = force_mode
            # FD cooldown override (V3b++ Phase 1b)
            fd_cooldown = getattr(args, "v3b_fd_cooldown", None)
            if fd_cooldown is not None:
                gate_cfg.full_divergence_cooldown_frames = fd_cooldown
            gate = VisualHealthGateV3b(gate_cfg)
            ad_path = exp_space.path("adaptive_decisions.csv")
            system.enable_adaptive(gate, decisions_csv_path=str(ad_path), version="v3b")
            Logger.write("info", f"Adaptive v3b enabled (force={force_mode or 'normal'}). Decisions → {ad_path}")
        elif getattr(args, "adaptive_v3a", False):
            from Utility.VisualHealthGateV3 import VisualHealthGateV3, VisualHealthGateV3Config
            gate_cfg = VisualHealthGateV3Config()
            force_mode = getattr(args, "v3a_force", "")
            if force_mode == "pure":
                gate_cfg.force_mode = "pure"
            elif force_mode == "full":
                gate_cfg.force_mode = "full"
            elif force_mode == "pure2latch":
                gate_cfg.force_pure_for_first_n_pairs = 2
                gate_cfg.latch_full_on_first_trigger = True
                gate_cfg.disable_exit_full = True
            elif force_mode == "latch":
                gate_cfg.latch_full_on_first_trigger = True
                gate_cfg.disable_exit_full = True
            gate = VisualHealthGateV3(gate_cfg)
            ad_path = exp_space.path("adaptive_decisions.csv")
            system.enable_adaptive(gate, decisions_csv_path=str(ad_path), version="v3a")
            Logger.write("info", f"Adaptive v3a enabled (force={force_mode or 'normal'}). Decisions → {ad_path}")
        elif getattr(args, "adaptive_v2", False):
            from Utility.VisualHealthGateV2 import VisualHealthGateV2, VisualHealthGateV2Config
            gate_cfg = VisualHealthGateV2Config()
            gate = VisualHealthGateV2(gate_cfg)
            ad_path = exp_space.path("adaptive_decisions.csv")
            system.enable_adaptive(gate, decisions_csv_path=str(ad_path), version="v2")
            Logger.write("info", f"Adaptive v2 enabled (flow_cov gate). Decisions → {ad_path}")
        elif getattr(args, "adaptive", False):
            from Utility.VisualHealthGate import VisualHealthGate, VisualHealthGateConfig
            gate_cfg = VisualHealthGateConfig()
            gate = VisualHealthGate(gate_cfg)
            ad_path = exp_space.path("adaptive_decisions.csv")
            system.enable_adaptive(gate, decisions_csv_path=str(ad_path))
            Logger.write("info", f"Adaptive v1 enabled (VisualHealthGate). Decisions → {ad_path}")

        system.receive_frames(sequence, exp_space, on_frame_finished=onFrameFinished)
        if _live_dashboard is not None:
            _live_dashboard.publish_system(system, None, "vio_committed")
        _diag_writer.close()

        if args.useRR:
            rr_plt.log_trajectory("/world/est", _load_saved_pose_se3(exp_space))
            try:
                rr_plt.log_points(
                    "/world/point_cloud",
                    system.get_map().map_points.data["pos_Tw"].tensor,
                    system.get_map().map_points.data["color"].tensor,
                    system.get_map().map_points.data["cov_Tw"].tensor,
                    "color",
                )
            except RuntimeError:
                Logger.write("warn", "Unable to log full pointcloud - is mapping mode on?")

        Timer.report()
        Timer.save_elapsed(exp_space.path("elapsed_time.json"))

        if not args.noeval:
            header, result = EvaluateSequences([str(exp_space.folder)], correct_scale=False)
            print_as_table(header, result)
    finally:
        if _online_pose_recorder is not None:
            _online_pose_recorder.close()
        if _diag_writer is not None:
            _diag_writer.close()
        if args.useRR:
            rr_plt.shutdown()
