args:
  auto_estimate_time_offset: true
  bl: 0.225
  batch_root: /mnt/e/文档/holoocean/code/recordings/batch_20260515_155653
  camera:
    cx: 320
    cy: 240
    fx: 320
    fy: 320
  format: png
  gravity: 9.8
  imu_T_BS:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  imu_fallback_max_dt_ns: -1
  imu_time_offset_ns: 0
  imu_window_ns: 100000000
  pose_output_frame: NWU
  root: /mnt/e/文档/holoocean/code/recordings/batch_20260515_155653/clear_shallow
  scene: clear_shallow
name: holoocean_imu
type: GeneralStereoIMU
