args:
  auto_estimate_time_offset: true
  batch_root: "/mnt/e/\u6587\u6863/holoocean/code/recordings/batch_20260515_155653"
  bl: 0.225
  camera:
    cx: 320
    cy: 240
    fx: 320
    fy: 320
  format: png
  gravity: 9.8
  imu_T_BS:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  imu_fallback_max_dt_ns: -1
  imu_time_offset_ns: 0
  imu_window_ns: 100000000
  pose_output_frame: NWU
  root: "/mnt/e/\u6587\u6863/holoocean/code/recordings/batch_20260515_155653/murky_coast"
  scene: clear_shallow
name: holoocean_imu
type: GeneralStereoIMU
