#!/usr/bin/env python3
"""Replay the short VIO segment with factors regenerated by the R2 visual restart."""

from __future__ import annotations

import csv
import json
import os
import runpy
import shutil
import sys
from pathlib import Path

import numpy as np
import pypose as pp
import torch
import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from Utility.RelativePoseFactorCache import (  # noqa: E402
    RelativePoseFactorCacheReader,
    RelativePoseFactorPacket,
    relative_pose_information_from_packet,
    write_relative_pose_factor_cache,
)
from Utility.VisualFactorCache import VisualFactorCacheReader  # noqa: E402
from Scripts.run_initialization_boundary_counterfactual import (  # noqa: E402
    ACTIVE_START,
    DATASET,
    FRAME_LIMIT,
    OUT,
    PREFIX_CACHE,
    read_poses,
    read_truth,
    short_metrics,
)


R2_VISUAL_RUN = OUT / "counterfactual_r2_visual_restart_result"
R2_FACTOR_CACHE = OUT / "counterfactual_r2_factor_cache_circle_391"
R2_ODOM_CONFIG = OUT / "counterfactual_r2_vio_sampling_aware.yaml"
R2_RUN_ROOT = OUT / "counterfactual_r2_vio_result"
R2_SUMMARY = OUT / "r2_vio_counterfactual_summary.json"
R0_RUN_ROOT = OUT / "counterfactual_r0_result"


def latest(root: Path, name: str) -> Path:
    candidates = sorted(root.rglob(name))
    if not candidates:
        raise FileNotFoundError(f"{root} has no {name}")
    return candidates[-1]


def prepare_factor_cache() -> None:
    if R2_FACTOR_CACHE.exists():
        shutil.rmtree(R2_FACTOR_CACHE)
    shutil.copytree(PREFIX_CACHE, R2_FACTOR_CACHE, copy_function=os.link)
    (R2_FACTOR_CACHE / "relative_pose_factors.npz").unlink(missing_ok=True)

    with np.load(latest(R2_VISUAL_RUN, "tensor_map.npz"), allow_pickle=False) as data:
        restarted_poses = pp.SE3(torch.from_numpy(data["frames//pose"].copy()).to(dtype=torch.float64))
    if restarted_poses.shape[0] != FRAME_LIMIT - ACTIVE_START:
        raise ValueError("R2 visual restart pose count is inconsistent")

    visual_reader = VisualFactorCacheReader(PREFIX_CACHE)
    original_factors = RelativePoseFactorCacheReader(PREFIX_CACHE)
    packets: list[RelativePoseFactorPacket] = []
    for frame_i in range(FRAME_LIMIT - 1):
        frame_j = frame_i + 1
        visual = visual_reader.load_pair(
            frame_i,
            frame_j,
            int(visual_reader.manifest.timestamps_ns[frame_i]),
            int(visual_reader.manifest.timestamps_ns[frame_j]),
        )
        if frame_i < ACTIVE_START:
            packets.append(original_factors.load_pair(frame_i, frame_j, visual.visual_sha256))
            continue
        local_i = frame_i - ACTIVE_START
        relative = restarted_poses[local_i : local_i + 1].Inv() @ restarted_poses[local_i + 1 : local_i + 2]
        covariance, diagnostics = relative_pose_information_from_packet(
            visual,
            relative.tensor(),
            huber_delta=3.0,
        )
        packets.append(
            RelativePoseFactorPacket(
                frame_i=frame_i,
                frame_j=frame_j,
                measurement_CiCj=relative.tensor().detach().cpu(),
                covariance=covariance.detach().cpu(),
                visual_sha256=visual.visual_sha256,
                num_points=int(diagnostics["num_points"]),
                num_inliers=int(diagnostics["num_inliers"]),
                mean_mahalanobis_sq=float(diagnostics["mean_mahalanobis_sq"]),
            )
        )
    write_relative_pose_factor_cache(R2_FACTOR_CACHE, packets)


def prepare_config() -> None:
    source = yaml.safe_load((OUT / "counterfactual_odometry_sampling_aware.yaml").read_text(encoding="utf-8"))
    source["Odometry"]["args"]["visual_cache_path"] = str(R2_FACTOR_CACHE)
    R2_ODOM_CONFIG.write_text(yaml.safe_dump(source, sort_keys=False), encoding="utf-8")


def bias_rows(tensor_path: Path) -> dict[str, np.ndarray]:
    with np.load(tensor_path, allow_pickle=False) as data:
        return {
            "ba": data["frames//imu_vio_acc_bias"].copy(),
            "bg": data["frames//imu_vio_gyro_bias"].copy(),
        }


def summarize() -> None:
    r2_pose_path = latest(R2_RUN_ROOT, "poses.csv")
    timestamps = [int(row["timestamp_ns"]) for row in csv.DictReader(r2_pose_path.open("r", encoding="utf-8"))]
    truth = read_truth(DATASET / "ref_pose.csv", timestamps)
    r2_metrics = short_metrics(read_poses(r2_pose_path), truth)
    r0_pose_path = OUT / "counterfactual_r0_poses.csv"
    r0_metrics = short_metrics(read_poses(r0_pose_path), truth)
    r0_bias = bias_rows(latest(R0_RUN_ROOT, "tensor_map.npz"))
    r2_bias = bias_rows(latest(R2_RUN_ROOT, "tensor_map.npz"))
    active_slice = slice(ACTIVE_START, FRAME_LIMIT)
    first30 = slice(ACTIVE_START, min(ACTIVE_START + 30, FRAME_LIMIT))
    summary = {
        "R0_metrics": r0_metrics,
        "R2_metrics": r2_metrics,
        "metric_difference_R2_minus_R0": {
            key: float(r2_metrics[key] - r0_metrics[key])
            for key in r0_metrics
            if key != "active_frame_count"
        },
        "first_edge_bias": {
            "R0_ba_after": r0_bias["ba"][ACTIVE_START].reshape(-1).tolist(),
            "R0_bg_after": r0_bias["bg"][ACTIVE_START].reshape(-1).tolist(),
            "R2_ba_after": r2_bias["ba"][ACTIVE_START].reshape(-1).tolist(),
            "R2_bg_after": r2_bias["bg"][ACTIVE_START].reshape(-1).tolist(),
        },
        "first_30_bias_max_absolute_difference": {
            "ba": float(np.max(np.abs(r2_bias["ba"][first30] - r0_bias["ba"][first30]))),
            "bg": float(np.max(np.abs(r2_bias["bg"][first30] - r0_bias["bg"][first30]))),
        },
        "active_bias_max_absolute_difference": {
            "ba": float(np.max(np.abs(r2_bias["ba"][active_slice] - r0_bias["ba"][active_slice]))),
            "bg": float(np.max(np.abs(r2_bias["bg"][active_slice] - r0_bias["bg"][active_slice]))),
        },
        "execution": "actual VIO replay with R2-regenerated visual mean and covariance",
    }
    R2_SUMMARY.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")


def main() -> int:
    if "--summarize-only" in sys.argv:
        summarize()
        print(R2_SUMMARY.read_text(encoding="utf-8"))
        return 0
    prepare_factor_cache()
    prepare_config()
    if R2_RUN_ROOT.exists():
        shutil.rmtree(R2_RUN_ROOT)
    sys.argv = [
        str(ROOT / "MACVO.py"),
        "--odom", str(R2_ODOM_CONFIG),
        "--data", str(OUT / "counterfactual_data_circle.yaml"),
        "--resultRoot", str(R2_RUN_ROOT),
        "--visual-cache-mode", "replay",
        "--visual-cache-path", str(R2_FACTOR_CACHE),
        "--seq_to", str(FRAME_LIMIT),
    ]
    runpy.run_path(str(ROOT / "MACVO.py"), run_name="__main__")
    summarize()
    print(R2_SUMMARY.read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
